Pins endpoint
poom201211/BackendFinalProject pull request #2
Opened 2021-03-08 13:59 UTC by poom201211

Wrote endpoint for pins including:
pin/?type=all
pin/?type=restaurant
pin/?type=cafe
pin/?type=attraction

2021-03-09 19:01 UTC, HAYATO-Kz requested changes, later dismissed

2021-03-09 19:01 UTC, HAYATO-Kz commented on api/controllers/pinController.js
> +    pin.find({}, (err, pin) => {
Always handle error

2021-03-09 19:01 UTC, HAYATO-Kz commented on api/controllers/pinController.js
> +      response.status(200).json(pin);
Don't forget to use return

2021-03-09 19:01 UTC, HAYATO-Kz commented on api/controllers/pinController.js
> +    pin.find({ type: req.query.type }, (err, pin) => {
Always handle error

2021-03-09 19:01 UTC, HAYATO-Kz commented on api/controllers/pinController.js
> +      response.status(200).json(pin);
Don't forget to use return

2021-03-10 04:18 UTC, poom201211 commented on api/controllers/pinController.js
> +    pin.find({}, (err, pin) => {
fixed

2021-03-10 04:18 UTC, poom201211 commented on api/controllers/pinController.js
> +      response.status(200).json(pin);
fixed

2021-03-10 04:18 UTC, poom201211 commented on api/controllers/pinController.js
> +    pin.find({ type: req.query.type }, (err, pin) => {
fixed

2021-03-10 04:18 UTC, poom201211 commented on api/controllers/pinController.js
> +      response.status(200).json(pin);
fixed

2021-03-10 11:23 UTC, HAYATO-Kz approved these changes

2021-03-10 11:24 UTC, merged